spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/optimapc_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:your-super-secret-key-change-in-production-with-at-least-32-characters-long}
jwt.expiration=86400000